# Script pour ajouter la modale des demandes déclinées dans le dashboard responsable

$filePath = "uasz-maintenance-frontend/src/app/pages/dashboard/dashboardResponsable/dashboard-responsable.component.html"

# Lire le contenu du fichier
$content = Get-Content $filePath -Raw -Encoding UTF8

# Rechercher la ligne avec "LIGHTBOX pour agrandir" et insérer avant
$lines = $content -split "`r?`n"
$newLines = @()
$inserted = $false

for ($i = 0; $i -lt $lines.Length; $i++) {
    $line = $lines[$i]
    
    # Si on trouve la ligne avec "LIGHTBOX pour agrandir", on insère la nouvelle modale avant
    if ($line -match "LIGHTBOX pour agrandir" -and !$inserted) {
        # Ajouter la nouvelle modale pour les demandes déclinées
        $newLines += ""
        $newLines += "        <!-- ========== MODAL ""DÉTAILS DEMANDE DÉCLINÉE"" (RESPONSABLE) ========== -->"
        $newLines += "        <div"
        $newLines += "          class=""modal-backdrop"""
        $newLines += "          *ngIf=""showDeclinedDetailsModal && selectedDeclinedDemande"""
        $newLines += "        >"
        $newLines += "          <section class=""modal-card"">"
        $newLines += "            <header class=""modal-header"">"
        $newLines += "              <h3>Détails de la demande déclinée</h3>"
        $newLines += "              <button type=""button"" class=""modal-close-btn"" (click)=""closeDeclinedDetailsModal()"">"
        $newLines += "                <span class=""material-icons"">close</span>"
        $newLines += "              </button>"
        $newLines += "            </header>"
        $newLines += ""
        $newLines += "            <div class=""modal-body"">"
        $newLines += "              <div class=""modal-main-title"">"
        $newLines += "                <h2>{{ selectedDeclinedDemande?.titre }}</h2>"
        $newLines += "                <p class=""modal-meta"">"
        $newLines += "                  Créée le {{ selectedDeclinedDemande?.dateCreation | date:'dd/MM/yyyy' }} · {{ selectedDeclinedDemande?.lieu }}"
        $newLines += "                </p>"
        $newLines += "              </div>"
        $newLines += ""
        $newLines += "              <div class=""modal-tags"">"
        $newLines += "                <div class=""modal-tag-item"">"
        $newLines += "                  <span class=""tag-label"">Statut</span>"
        $newLines += "                  <span class=""status-pill cancelled"">"
        $newLines += "                    Déclinée"
        $newLines += "                  </span>"
        $newLines += "                </div>"
        $newLines += ""
        $newLines += "                <div class=""modal-tag-item"">"
        $newLines += "                  <span class=""tag-label"">Urgence</span>"
        $newLines += "                  <span class=""urgency-pill"" [ngClass]=""getUrgenceListClassAny(selectedDeclinedDemande?.urgence)"">"
        $newLines += "                    {{ libelleUrgence(selectedDeclinedDemande?.urgence) }}"
        $newLines += "                  </span>"
        $newLines += "                </div>"
        $newLines += ""
        $newLines += "                <div class=""modal-tag-item"">"
        $newLines += "                  <span class=""tag-label"">Type d'équipement</span>"
        $newLines += "                  <span class=""place-chip"">{{ selectedDeclinedDemande?.typeEquipement }}</span>"
        $newLines += "                </div>"
        $newLines += "              </div>"
        $newLines += ""
        $newLines += "              <div class=""modal-section"" *ngIf=""selectedDeclinedDemande?.description; else noDeclinedDesc"">"
        $newLines += "                <h4>Description</h4>"
        $newLines += "                <p class=""description-text"">{{ selectedDeclinedDemande?.description }}</p>"
        $newLines += "              </div>"
        $newLines += "              <ng-template #noDeclinedDesc>"
        $newLines += "                <div class=""modal-section"">"
        $newLines += "                  <h4>Description</h4>"
        $newLines += "                  <p class=""modal-help"" style=""color: #6b7280; font-style: italic;"">Aucune description</p>"
        $newLines += "                </div>"
        $newLines += "              </ng-template>"
        $newLines += ""
        $newLines += "              <!-- Informations de déclin -->"
        $newLines += "              <div class=""modal-section"">"
        $newLines += "                <h4>Informations de déclin</h4>"
        $newLines += "                "
        $newLines += "                <div class=""decline-info-box"">"
        $newLines += "                  <div class=""decline-info-row"" *ngIf=""selectedDeclinedDemande?.dateRefus"">"
        $newLines += "                    <span class=""decline-label"">Date du déclin :</span>"
        $newLines += "                    <span class=""decline-value"">{{ selectedDeclinedDemande?.dateRefus | date:'dd/MM/yyyy à HH:mm' }}</span>"
        $newLines += "                  </div>"
        $newLines += "                  "
        $newLines += "                  <div class=""decline-info-row"" *ngIf=""selectedDeclinedDemande?.technicienNom || selectedDeclinedDemande?.technicienPrenom"">"
        $newLines += "                    <span class=""decline-label"">Décliné par :</span>"
        $newLines += "                    <span class=""decline-value"">"
        $newLines += "                      {{ selectedDeclinedDemande?.technicienPrenom }} {{ selectedDeclinedDemande?.technicienNom }}"
        $newLines += "                    </span>"
        $newLines += "                  </div>"
        $newLines += "                  "
        $newLines += "                  <div class=""decline-info-row"" *ngIf=""selectedDeclinedDemande?.raisonRefus"">"
        $newLines += "                    <span class=""decline-label"">Raison du déclin :</span>"
        $newLines += "                    <p class=""decline-reason"">{{ selectedDeclinedDemande?.raisonRefus }}</p>"
        $newLines += "                  </div>"
        $newLines += "                  "
        $newLines += "                  <div *ngIf=""!selectedDeclinedDemande?.raisonRefus && !selectedDeclinedDemande?.dateRefus"">"
        $newLines += "                    <p class=""modal-help"" style=""color: #6b7280; font-style: italic;"">"
        $newLines += "                      Aucune information de déclin disponible."
        $newLines += "                    </p>"
        $newLines += "                  </div>"
        $newLines += "                </div>"
        $newLines += "              </div>"
        $newLines += ""
        $newLines += "              <div class=""modal-section"">"
        $newLines += "                <h4>Image jointe</h4>"
        $newLines += "                "
        $newLines += "                <div *ngIf=""selectedDeclinedDemande?.imageUrl; else noDeclinedImage"">"
        $newLines += "                  <button"
        $newLines += "                    type=""button"""
        $newLines += "                    class=""secondary-btn small pagination-btn"""
        $newLines += "                    (click)=""toggleDeclinedImageDetails()"""
        $newLines += "                  >"
        $newLines += "                    {{ showDeclinedImageInDetails ? ""Masquer l'image"" : ""Afficher l'image"" }}"
        $newLines += "                  </button>"
        $newLines += ""
        $newLines += "                  <div class=""panne-image-wrapper"" *ngIf=""showDeclinedImageInDetails"">"
        $newLines += "                    <img"
        $newLines += "                      [src]=""selectedDeclinedDemande?.imageUrl"""
        $newLines += "                      alt=""Image de la demande"""
        $newLines += "                      (click)=""openImageLightbox(selectedDeclinedDemande?.imageUrl!)"""
        $newLines += "                      style=""cursor: pointer;"""
        $newLines += "                    />"
        $newLines += "                  </div>"
        $newLines += "                </div>"
        $newLines += ""
        $newLines += "                <ng-template #noDeclinedImage>"
        $newLines += "                  <p class=""modal-help"" style=""color: #6b7280; font-style: italic;"">"
        $newLines += "                    Aucune image jointe"
        $newLines += "                  </p>"
        $newLines += "                </ng-template>"
        $newLines += "              </div>"
        $newLines += "            </div>"
        $newLines += ""
        $newLines += "            <footer class=""modal-footer"">"
        $newLines += "              <button type=""button"" class=""secondary-btn small pagination-btn"" (click)=""closeDeclinedDetailsModal()"">"
        $newLines += "                Fermer"
        $newLines += "              </button>"
        $newLines += "            </footer>"
        $newLines += "          </section>"
        $newLines += "        </div>"
        $newLines += ""
        $inserted = $true
    }
    
    $newLines += $line
}

# Écrire le nouveau contenu
$newContent = $newLines -join "`n"
Set-Content $filePath -Value $newContent -Encoding UTF8

if ($inserted) {
    Write-Host "✅ Modale des demandes déclinées ajoutée avec succès dans le dashboard responsable"
} else {
    Write-Host "❌ Ligne cible non trouvée"
}