# ================= DATASOURCE DEV =================
spring.datasource.url=jdbc:postgresql://localhost:5432/maintenance_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:ouz4real}
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA DEV =================
spring.jpa.show-sql=true

# ================= CORS DEV =================
app.cors.allowed-origins=http://localhost:4200

# ================= LOGS DEV =================
logging.level.sn.uasz=DEBUG
logging.level.org.springframework.security=DEBUG
