spring.application.name=uasz-maintenance-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/maintenance_db
spring.datasource.username=postgres
spring.datasource.password=ouz4real
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ================= JWT =================
app.jwt.secret=VGhpc0lzQVVBU1pNYWludGVuYW5jZUFwcFNlY3JldEtleTEyMzQ1Ng==
# 1 jour en millisecondes
app.jwt.expiration=86400000
# Cle secrete JWT (au moins 32 caracteres)
application.security.jwt.secret=MaSuperCleUltraSecretePourUASZMaintenance123!

# Duree de validite du token en millisecondes (ici : 24h)
application.security.jwt.expiration=86400000

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maneouz185@gmail.com
spring.mail.password=rbdatvesaliabdod
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Email de l'application
app.email.from=noreply@uasz-maintenance.sn
app.email.enabled=true

