# ================= DATASOURCE PROD =================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA PROD =================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# ================= CORS PROD =================
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://uasz-maintenance.sn}

# ================= LOGS PROD =================
logging.level.sn.uasz=WARN
logging.level.org.springframework=WARN
logging.level.root=ERROR
