[build]
  base    = ""
  command = "npm run build -- --configuration production"
  publish = "dist/uasz-maintenance-frontend/browser"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
